DATASET:
  FOLDER_NAME: full_dataset_start=350_interval=100_ndraw=8_size=(64,64)
  IMG_TYPES:
  - cells_types
  - cells_densities
  - oxygen
  - glucose
  N_DRAWS: 4
  PARAMETERS_OF_INTEREST:
  - average_healthy_glucose_absorption
  - average_cancer_glucose_absorption
  - average_healthy_oxygen_consumption
  - average_cancer_oxygen_consumption
  - cell_cycle
MODEL:
  CONV_LAYERS: 4
  FEED_FORWARD: 200
  INPUT_LSTM: 200
  LSTM_LAYERS: 1
  OUTPUT_LSTM: 200
TRAINING:
  BATCH_SIZE: 1
  EARLY_STOPPING_MIN_DELTA: 0.001
  EARLY_STOPPING_PATIENCE: 10
  EPOCH: 300
  L2_REGULARIZATION: 0.001
  LEARNING_RATE: 0.0001
