---
DATASET:
  FOLDER_NAME: cell_cycle_start=350_interval=100_ndraw=8_size=(64,64)
  N_DRAWS: 4
  IMG_TYPES:
    - cells_types
    - cells_densities
    - oxygen
    - glucose
  PARAMETERS_OF_INTEREST:
    - cell_cycle

MODEL:
  INPUT_LSTM: 100
  OUTPUT_LSTM: 100
  LSTM_LAYERS: 1
  CONV_LAYERS: 4

TRAINING:
  LEARNING_RATE: 0.0001
  EPOCH: 25
  BATCH_SIZE: 10
  DEVICE: cpu

