---
NAME: basic_multi_process
DATASET:
  FOLDER_NAME: basic_multiprocess_start=350_interval=100_ndraw=4_size=(64,64)
  N_DRAWS: 4
  IMG_TYPES:
    - cells_types
    - cells_densities
    - oxygen
    - glucose
  PARAMETERS_OF_INTEREST:
    - cell_cycle

MODEL:
  INPUT_LSTM: 100
  OUTPUT_LSTM: 100

TRAINING:
  LEARNING_RATE: 0.001
  EPOCH: 50
  BATCH_SIZE: 10
  DEVICE: cpu

